//******************************************************************************
// Copyright (c) 2019 - 2019, The Regents of the University of California (Regents).
// All Rights Reserved. See LICENSE and LICENSE.SiFive for license details.
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// CVA6 Tile Wrapper
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

package cva6

import chisel3._
import chisel3.util._
import chisel3.experimental.{IntParam, StringParam}

import scala.collection.mutable.{ListBuffer}
import java.io.{File, FileWriter}

import org.chipsalliance.cde.config._
import freechips.rocketchip.subsystem._
import freechips.rocketchip.devices.tilelink._
import freechips.rocketchip.diplomacy._
import freechips.rocketchip.prci._
import freechips.rocketchip.rocket._
import freechips.rocketchip.subsystem.{RocketCrossingParams}
import freechips.rocketchip.tilelink._
import freechips.rocketchip.interrupts._
import freechips.rocketchip.util._
import freechips.rocketchip.tile._
import freechips.rocketchip.amba.axi4._

object CVA6ConfigPackageGenerator {
  def generatePackage(params: CVA6CoreParams, targetPath: String): Unit = {
    val writer = new java.io.FileWriter(new File(targetPath))
    
    val dCacheTypeSv = if (params.dCacheType == "WT") "config_pkg::WT" else "config_pkg::WB"

    writer.write(s"""// AUTO-GENERATED BY CHIPYARD SCALA GENERATOR
// Mapping all CVA6 Core Parameters

package cva6_config_pkg;
  import config_pkg::*; // Ensure definitions are visible
  import build_config_pkg::*;

  localparam CVA6ConfigXlen = ${params.xLen};

  localparam CVA6ConfigRVF = ${if (params.useFPU) 1 else 0};
  localparam CVA6ConfigF16En = ${if (params.useF16) 1 else 0};
  localparam CVA6ConfigF16AltEn = 0;
  localparam CVA6ConfigF8En = 0;
  localparam CVA6ConfigFVecEn = 0;

  localparam CVA6ConfigCvxifEn = 0;
  localparam CVA6ConfigCExtEn = ${if (params.useCompressed) 1 else 0};
  localparam CVA6ConfigZcbExtEn = 0;
  localparam CVA6ConfigZcmpExtEn = 0;
  localparam CVA6ConfigAExtEn = ${if (params.useAtomics) 1 else 0};
  localparam CVA6ConfigBExtEn = ${if (params.useBExt) 1 else 0};
  localparam CVA6ConfigHExtEn = 0;
  localparam CVA6ConfigVExtEn = ${if (params.useVector) 1 else 0};
  localparam CVA6ConfigRVZiCond = 0;

  localparam CVA6ConfigAxiIdWidth = ${params.axiIdWidth};
  localparam CVA6ConfigAxiAddrWidth = ${params.axiAddrWidth};
  localparam CVA6ConfigAxiDataWidth = ${params.axiDataWidth};
  localparam CVA6ConfigFetchUserEn = 0;
  localparam CVA6ConfigFetchUserWidth = CVA6ConfigXlen;
  localparam CVA6ConfigDataUserEn = 0;
  localparam CVA6ConfigDataUserWidth = CVA6ConfigXlen;

  localparam CVA6ConfigIcacheByteSize = ${params.iCacheByteSize};
  localparam CVA6ConfigIcacheSetAssoc =  ${params.iCacheSetAssoc} ;
  localparam CVA6ConfigIcacheLineWidth = ${params.iCacheLineWidth};
  localparam CVA6ConfigDcacheByteSize = ${params.dCacheByteSize};
  localparam CVA6ConfigDcacheSetAssoc = ${params.dCacheSetAssoc};
  localparam CVA6ConfigDcacheLineWidth = ${params.dCacheLineWidth};

  localparam CVA6ConfigDcacheFlushOnFence = 1'b0;
  localparam CVA6ConfigDcacheInvalidateOnFlush = 1'b0;
  localparam CVA6ConfigDcacheIdWidth = 1;
  localparam CVA6ConfigMemTidWidth = 2;
  localparam CVA6ConfigWtDcacheWbufDepth = ${params.wtDcacheWbufDepth};

  localparam CVA6ConfigNrScoreboardEntries = ${params.nrScoreboardEntries};
  localparam CVA6ConfigNrLoadPipeRegs = ${params.nrLoadPipeRegs};
  localparam CVA6ConfigNrStorePipeRegs = ${params.nrStorePipeRegs};
  localparam CVA6ConfigNrLoadBufEntries = ${params.nrLoadBufEntries};

  localparam CVA6ConfigRASDepth = ${params.rasEntries};
  localparam CVA6ConfigBTBEntries = ${params.btbEntries};
  localparam CVA6ConfigBHTEntries = ${params.bhtEntries};

  localparam CVA6ConfigTvalEn = 0;
  localparam CVA6ConfigNrPMPEntries = ${params.pmpEntries};
  localparam CVA6ConfigPerfCounterEn = 0;
  localparam config_pkg::cache_type_t CVA6ConfigDcacheType = $dCacheTypeSv;
  localparam CVA6ConfigMmuPresent = ${if (params.mmuPresent) 1 else 0};
  localparam CVA6ConfigRvfiTrace = 0;
  
  localparam config_pkg::cva6_user_cfg_t cva6_cfg = '{
      XLEN: unsigned'(CVA6ConfigXlen),
      VLEN: unsigned'(64),
      
      // --- RISC-V Extensions ---
      RVA: bit'(CVA6ConfigAExtEn),
      RVB: bit'(CVA6ConfigBExtEn),
      ZKN: 1'b0,                  
      RVV: bit'(CVA6ConfigVExtEn),
      RVC: bit'(CVA6ConfigCExtEn),
      RVH: 1'b0,                  
      RVZCB: 1'b0,                
      RVZCMP: 1'b0,               
      RVZCMT: 1'b0,               
      RVZiCond: bit'(CVA6ConfigRVZiCond),
      RVZicntr: 1'b1,             
      RVZihpm: 1'b1,              
      RVF: bit'(CVA6ConfigRVF),
      RVD: bit'(CVA6ConfigRVF),
      XF16: bit'(CVA6ConfigF16En),
      XF16ALT: bit'(CVA6ConfigF16AltEn),
      XF8: bit'(CVA6ConfigF8En),
      XFVec: bit'(CVA6ConfigFVecEn),

      // --- Security & Privileged ---
      PerfCounterEn: bit'(CVA6ConfigPerfCounterEn),
      MmuPresent: bit'(CVA6ConfigMmuPresent),
      RVS: 1'b1,                  
      RVU: 1'b1,                  
      SoftwareInterruptEn: 1'b1,  
      DebugEn: 1'b1,              
      DmBaseAddress: 64'h0,       
      HaltAddress: 64'h800,
      ExceptionAddress: 64'h808,
      TvalEn: bit'(CVA6ConfigTvalEn),
      DirectVecOnly: 1'b0,        

      // --- PMP & PMA ---
      NrPMPEntries: unsigned'(CVA6ConfigNrPMPEntries),
      PMPCfgRstVal: '0,           
      PMPAddrRstVal: '0,          
      PMPEntryReadOnly: '0,       
      PMPNapotEn: 1'b1,           
      NrNonIdempotentRules: 0,    
      NonIdempotentAddrBase: '0,  
      NonIdempotentLength: '0,    
      NrExecuteRegionRules: 0,    
      ExecuteRegionAddrBase: '0,  
      ExecuteRegionLength: '0,    
      NrCachedRegionRules: 0,     
      CachedRegionAddrBase: '0,   
      CachedRegionLength: '0,     

      // --- Interface & Bus ---
      CvxifEn: bit'(CVA6ConfigCvxifEn),
      NOCType: config_pkg::NOC_TYPE_AXI4_ATOP,   
      AxiAddrWidth: unsigned'(CVA6ConfigAxiAddrWidth),
      AxiDataWidth: unsigned'(CVA6ConfigAxiDataWidth),
      AxiIdWidth: unsigned'(CVA6ConfigAxiIdWidth),
      AxiUserWidth: unsigned'(1),            
      AxiBurstWriteEn: 1'b0,      
      MemTidWidth: unsigned'(CVA6ConfigMemTidWidth),

      // --- Cache ---
      IcacheByteSize: unsigned'(CVA6ConfigIcacheByteSize),
      IcacheSetAssoc: unsigned'(CVA6ConfigIcacheSetAssoc),
      IcacheLineWidth: unsigned'(CVA6ConfigIcacheLineWidth),
      DCacheType: CVA6ConfigDcacheType,
      DcacheIdWidth: unsigned'(CVA6ConfigDcacheIdWidth),
      DcacheByteSize: unsigned'(CVA6ConfigDcacheByteSize),
      DcacheSetAssoc: unsigned'(CVA6ConfigDcacheSetAssoc),
      DcacheLineWidth: unsigned'(CVA6ConfigDcacheLineWidth),
      DcacheFlushOnFence: bit'(CVA6ConfigDcacheFlushOnFence),
      DcacheInvalidateOnFlush: bit'(CVA6ConfigDcacheInvalidateOnFlush),
      
      // --- Optimization & Pipeline ---
      DataUserEn: unsigned'(CVA6ConfigDataUserEn),
      WtDcacheWbufDepth: unsigned'(CVA6ConfigWtDcacheWbufDepth),
      FetchUserEn: unsigned'(CVA6ConfigFetchUserEn),
      FetchUserWidth: unsigned'(CVA6ConfigFetchUserWidth),
      FpgaEn: bit'(0),
      FpgaAlteraEn: 1'b0,         
      TechnoCut: 1'b1,            
      SuperscalarEn: 1'b0,        
      NrCommitPorts: unsigned'(2),
      NrLoadPipeRegs: int'(CVA6ConfigNrLoadPipeRegs),
      NrStorePipeRegs: int'(CVA6ConfigNrStorePipeRegs),
      NrScoreboardEntries: unsigned'(CVA6ConfigNrScoreboardEntries),
      NrLoadBufEntries: unsigned'(CVA6ConfigNrLoadBufEntries),
      MaxOutstandingStores: 7,    

      // --- Branch Prediction & TLB ---
      RASDepth: unsigned'(CVA6ConfigRASDepth),
      BTBEntries: unsigned'(CVA6ConfigBTBEntries),
      BHTEntries: unsigned'(CVA6ConfigBHTEntries),
      InstrTlbEntries: 16,        
      DataTlbEntries: 16,         
      UseSharedTlb: 1'b0,         
      SharedTlbDepth: 64          
    };
    
    localparam config_pkg::cva6_cfg_t cva6_soc_cfg = build_config_pkg::build_config(cva6_cfg);

endpackage
""")
    writer.close()
  }
}

case class CVA6CoreParams(
  // Constructor parameters (External configuration)
  override val xLen: Int = 64,
  override val vLen: Int = 64,        
  val bootFreqHz: BigInt = BigInt(1700000000),
  val rasEntries: Int = 2,
  val btbEntries: Int = 32,
  val bhtEntries: Int = 128,
  val nrScoreboardEntries: Int = 8,
  val nrLoadPipeRegs: Int = 1,
  val nrStorePipeRegs: Int = 0,
  val nrLoadBufEntries: Int = 2,
  override val retireWidth: Int = 1,
  override val useVector: Boolean = false,
  val useFPU: Boolean = false,
  val useF16: Boolean = false,
  override val useAtomics: Boolean = true,
  override val useCompressed: Boolean = true,
  val useBExt: Boolean = false,
  val iCacheByteSize: Int = 2048,
  val iCacheSetAssoc: Int = 4,
  val iCacheLineWidth: Int = 128,
  val dCacheByteSize: Int = 2048,
  val dCacheSetAssoc: Int = 8,
  val dCacheLineWidth: Int = 128,
  val dCacheType: String = "WT",
  val wtDcacheWbufDepth: Int = 8,
  val pmpEntries: Int = 8,
  val mmuPresent: Boolean = true,
  val axiIdWidth: Int = 4,
  val axiAddrWidth: Int = 64,
  val axiDataWidth: Int = 64,
  val enableToFromHostCaching: Boolean = false
) extends CoreParams {
  // Implementation of missing CoreParams trait members

  override def eLen: Int = 64           

  override val useVM: Boolean = true
  override val useHypervisor: Boolean = false
  override val useUser: Boolean = true
  override val useSupervisor: Boolean = true
  override val useDebug: Boolean = true
  override val nPMPs: Int = pmpEntries
  override val nPerfCounters: Int = 29
  override val decodeWidth: Int = 1
  override val fetchWidth: Int = 1
  override val instBits: Int = if (useCompressed) 16 else 32
  override val pgLevels: Int = if (xLen == 64) 3 else 2

  // Mandatory Rocket Chip trait members (defaults for CVA6)
  val fpu: Option[FPUParams] = if (useFPU) Some(FPUParams()) else None
  val haveBasicCounters: Boolean = true
  val haveCFlush: Boolean = false
  val haveFSDirty: Boolean = false
  val lrscCycles: Int = 80
  val mcontextWidth: Int = 0
  val misaWritable: Boolean = false
  val mtvecInit: Option[BigInt] = Some(BigInt(0))
  val mtvecWritable: Boolean = true
  val mulDiv: Option[freechips.rocketchip.rocket.MulDivParams] = Some(MulDivParams())
  val nBreakpoints: Int = 0
  val nL2TLBEntries: Int = 512
  val nL2TLBWays: Int = 1
  val nLocalInterrupts: Int = 0
  val nPTECacheEntries: Int = 8
  val pmpGranularity: Int = 4
  val scontextWidth: Int = 0
  val traceHasWdata: Boolean = false
  val useAtomicsOnlyForIO: Boolean = false
  val useBPWatch: Boolean = false
  val useConditionalZero: Boolean = false
  val useNMI: Boolean = false
  val useRVE: Boolean = false
  val useZba: Boolean = false
  val useZbb: Boolean = false
  val useZbs: Boolean = false
}

case class CVA6TileAttachParams(
  tileParams: CVA6TileParams,
  crossingParams: RocketCrossingParams
) extends CanAttachTile {
  type TileType = CVA6Tile
  val lookup = PriorityMuxHartIdFromSeq(Seq(tileParams))
}

case class CVA6TileParams(
  name: Option[String] = Some("cva6_tile"),
  tileId: Int = 0,
  trace: Boolean = false,
  val core: CVA6CoreParams = CVA6CoreParams()
) extends InstantiableTileParams[CVA6Tile]
{
  val beuAddr: Option[BigInt] = None
  val blockerCtrlAddr: Option[BigInt] = None
  val btb: Option[BTBParams] = Some(BTBParams(nEntries = core.btbEntries))
  val boundaryBuffers: Boolean = false
  
  // MATCH THE CACHE PARAMS TO THE CORE PARAMS
  val dcache: Option[DCacheParams] = Some(DCacheParams(
    rowBits = core.dCacheLineWidth, 
    nSets = core.dCacheByteSize / (core.dCacheLineWidth / 8) / core.dCacheSetAssoc, 
    nWays = core.dCacheSetAssoc))
    
  val icache: Option[ICacheParams] = Some(ICacheParams(
    rowBits = core.iCacheLineWidth, 
    nSets = core.iCacheByteSize / (core.iCacheLineWidth / 8) / core.iCacheSetAssoc, 
    nWays = core.iCacheSetAssoc))

  val clockSinkParams: ClockSinkParameters = ClockSinkParameters()
  def instantiate(crossing: HierarchicalElementCrossingParamsLike, lookup: LookupByHartIdImpl)(implicit p: Parameters): CVA6Tile = {
    new CVA6Tile(this, crossing, lookup)
  }
  val baseName = name.getOrElse("cva6_tile")
  val uniqueName = s"${baseName}_$tileId"
}


class CVA6Tile private(
  val cva6Params: CVA6TileParams,
  crossing: ClockCrossingType,
  lookup: LookupByHartIdImpl,
  q: Parameters)
  extends BaseTile(cva6Params, crossing, lookup, q)
  with SinksExternalInterrupts
  with SourcesExternalNotifications
{
  /**
   * Setup parameters:
   * Private constructor ensures altered LazyModule.p is used implicitly
   */
  def this(params: CVA6TileParams, crossing: HierarchicalElementCrossingParamsLike, lookup: LookupByHartIdImpl)(implicit p: Parameters) =
    this(params, crossing.crossingType, lookup, p)

  val intOutwardNode = None
  val slaveNode = TLIdentityNode()
  val masterNode = visibilityNode

  tlOtherMastersNode := tlMasterXbar.node
  masterNode :=* tlOtherMastersNode
  DisableMonitors { implicit p => tlSlaveXbar.node :*= slaveNode }

  val cpuDevice: SimpleDevice = new SimpleDevice("cpu", Seq("openhwgroup,cva6", "riscv")) {
    override def parent = Some(ResourceAnchors.cpus)
    override def describe(resources: ResourceBindings): Description = {
      val Description(name, mapping) = super.describe(resources)
      Description(name, mapping ++
                        cpuProperties ++
                        nextLevelCacheProperty ++
                        tileProperties)
    }
  }

  ResourceBinding {
    Resource(cpuDevice, "reg").bind(ResourceAddress(tileId))
  }

 override def makeMasterBoundaryBuffers(crossing: ClockCrossingType)(implicit p: Parameters) = crossing match {
    case _: RationalCrossing =>
      if (!cva6Params.boundaryBuffers) TLBuffer(BufferParams.none)
      else TLBuffer(BufferParams.none, BufferParams.flow, BufferParams.none, BufferParams.flow, BufferParams(1))
    case _ => TLBuffer(BufferParams.none)
  }

  override def makeSlaveBoundaryBuffers(crossing: ClockCrossingType)(implicit p: Parameters) = crossing match {
    case _: RationalCrossing =>
      if (!cva6Params.boundaryBuffers) TLBuffer(BufferParams.none)
      else TLBuffer(BufferParams.flow, BufferParams.none, BufferParams.none, BufferParams.none, BufferParams.none)
    case _ => TLBuffer(BufferParams.none)
  }

  override lazy val module = new CVA6TileModuleImp(this)
  
  val svPath = "generators/cva6/src/main/resources/cva6/vsrc/cva6_config_pkg.sv"
  CVA6ConfigPackageGenerator.generatePackage(cva6Params.core, svPath)

  /**
   * Setup AXI4 memory interface.
   * THESE ARE CONSTANTS.
   */
  val portName = "cva6-mem-port-axi4"
  val idBits = 4
  val beatBytes = masterPortBeatBytes
  val sourceBits = 1 // equiv. to userBits (i think)

  val memAXI4Node = AXI4MasterNode(
    Seq(AXI4MasterPortParameters(
      masters = Seq(AXI4MasterParameters(
        name = portName,
        id = IdRange(0, 1 << idBits))))))

  val memoryTap = TLIdentityNode()
  (tlMasterXbar.node
    := memoryTap
    := TLBuffer()
    := TLFIFOFixer(TLFIFOFixer.all) // fix FIFO ordering
    := TLWidthWidget(beatBytes) // reduce size of TL
    := AXI4ToTL() // convert to TL
    := AXI4UserYanker(Some(2)) // remove user field on AXI interface. need but in reality user intf. not needed
    := AXI4Fragmenter() // deal with multi-beat xacts
    := memAXI4Node)

  def connectCVA6Interrupts(debug: Bool, msip: Bool, mtip: Bool, m_s_eip: UInt): Unit = {
    val (interrupts, _) = intSinkNode.in(0)
    debug := interrupts(0)
    msip := interrupts(1)
    mtip := interrupts(2)
    m_s_eip := Cat(interrupts(4), interrupts(3))
  }
}

class CVA6TileModuleImp(outer: CVA6Tile) extends BaseTileModuleImp(outer){
  val debugBaseAddr = BigInt(0x0) // CONSTANT: based on default debug module
  val debugSz = BigInt(0x1000) // CONSTANT: based on default debug module
  val tohostAddr = BigInt(0x80001000L) // CONSTANT: based on default sw (assume within extMem region)
  val fromhostAddr = BigInt(0x80001040L) // CONSTANT: based on default sw (assume within extMem region)

  // have the main memory, bootrom, debug regions be executable
  val bootromParams = p(BootROMLocated(InSubsystem)).head
  val executeRegionBases = Seq(p(ExtMem).get.master.base,      bootromParams.address, debugBaseAddr, BigInt(0x0), BigInt(0x0))
  val executeRegionSzs   = Seq(p(ExtMem).get.master.size, BigInt(bootromParams.size),       debugSz, BigInt(0x0), BigInt(0x0))
  val executeRegionCnt   = executeRegionBases.length

  // have the main memory be cached, but don't cache tohost/fromhost addresses
  // TODO: current cache subsystem can only support 1 cacheable region... so cache AFTER the tohost/fromhost addresses
  val wordOffset = 0x40
  val (cacheableRegionBases, cacheableRegionSzs) = if (outer.cva6Params.core.enableToFromHostCaching) {
    val bases = Seq(p(ExtMem).get.master.base, BigInt(0x0), BigInt(0x0), BigInt(0x0), BigInt(0x0))
    val sizes   = Seq(p(ExtMem).get.master.size, BigInt(0x0), BigInt(0x0), BigInt(0x0), BigInt(0x0))
    (bases, sizes)
  } else {
    val bases = Seq(                                                          fromhostAddr + 0x40,              p(ExtMem).get.master.base, BigInt(0x0), BigInt(0x0), BigInt(0x0))
    val sizes = Seq(p(ExtMem).get.master.size - (fromhostAddr + 0x40 - p(ExtMem).get.master.base), tohostAddr - p(ExtMem).get.master.base, BigInt(0x0), BigInt(0x0), BigInt(0x0))
    (bases, sizes)
  }
  val cacheableRegionCnt   = cacheableRegionBases.length

  // Add 2 to account for the extra clock and reset included with each
  // instruction in the original trace port implementation. These have since
  // been removed from TracedInstruction.
  // Force to zero for synthesis fix
  val traceInstSz = 1

  // connect the cva6 core
  val core = Module(new CVA6CoreBlackbox(
    traceportEnabled = outer.cva6Params.trace,
    traceportSz = traceInstSz,
    xLen = outer.cva6Params.core.xLen,
    vLen = outer.cva6Params.core.vLen,
    rasEntries = outer.cva6Params.core.rasEntries,
    btbEntries = outer.cva6Params.core.btbEntries,
    bhtEntries = outer.cva6Params.core.bhtEntries,
    nrScoreboardEntries = outer.cva6Params.core.nrScoreboardEntries,
    nrLoadPipeRegs = outer.cva6Params.core.nrLoadPipeRegs,
    nrStorePipeRegs = outer.cva6Params.core.nrStorePipeRegs,
    nrLoadBufEntries = outer.cva6Params.core.nrLoadBufEntries,
    pmpEntries = outer.cva6Params.core.pmpEntries,
    iCacheByteSize = outer.cva6Params.core.iCacheByteSize,
    iCacheSetAssoc = outer.cva6Params.core.iCacheSetAssoc,
    dCacheByteSize = outer.cva6Params.core.dCacheByteSize,
    dCacheSetAssoc = outer.cva6Params.core.dCacheSetAssoc,
    
    // Memory region params
    exeRegCnt = executeRegionCnt,
    exeRegBase = executeRegionBases,
    exeRegSz = executeRegionSzs,
    cacheRegCnt = cacheableRegionCnt,
    cacheRegBase = cacheableRegionBases,
    cacheRegSz = cacheableRegionSzs,
    
    debugBase = debugBaseAddr,
    axiAddrWidth = 64,
    axiDataWidth = outer.beatBytes * 8,
    axiUserWidth = outer.sourceBits,
    axiIdWidth = outer.idBits
  ))
  
  core.io.clk_i := clock
  core.io.rst := reset.asBool
  core.io.boot_addr_i := outer.resetVectorSinkNode.bundle
  core.io.hart_id_i := outer.hartIdSinkNode.bundle

  outer.connectCVA6Interrupts(core.io.debug_req_i, core.io.ipi_i, core.io.time_irq_i, core.io.irq_i)

  if (outer.cva6Params.trace) {
    // unpack the trace io from a UInt into Vec(TracedInstructions)
    //outer.traceSourceNode.bundle <> core.io.trace_o.asTypeOf(outer.traceSourceNode.bundle)

    for (w <- 0 until outer.cva6Params.core.retireWidth) {
      outer.traceSourceNode.bundle.insns(w).valid     := core.io.trace_o(traceInstSz*w + 2)
      outer.traceSourceNode.bundle.insns(w).iaddr     := core.io.trace_o(traceInstSz*w + 42, traceInstSz*w + 3)
      outer.traceSourceNode.bundle.insns(w).insn      := core.io.trace_o(traceInstSz*w + 74, traceInstSz*w + 43)
      outer.traceSourceNode.bundle.insns(w).priv      := core.io.trace_o(traceInstSz*w + 77, traceInstSz*w + 75)
      outer.traceSourceNode.bundle.insns(w).exception := core.io.trace_o(traceInstSz*w + 78)
      outer.traceSourceNode.bundle.insns(w).interrupt := core.io.trace_o(traceInstSz*w + 79)
      outer.traceSourceNode.bundle.insns(w).cause     := core.io.trace_o(traceInstSz*w + 87, traceInstSz*w + 80)
      outer.traceSourceNode.bundle.insns(w).tval      := core.io.trace_o(traceInstSz*w + 127, traceInstSz*w + 88)
    }
  } else {
    outer.traceSourceNode.bundle := DontCare
    outer.traceSourceNode.bundle.insns map (t => t.valid := false.B)
  }

  // connect the axi interface
  outer.memAXI4Node.out foreach { case (out, edgeOut) =>
    core.io.axi_resp_i_aw_ready    := out.aw.ready
    out.aw.valid                   := core.io.axi_req_o_aw_valid
    out.aw.bits.id                 := core.io.axi_req_o_aw_bits_id
    out.aw.bits.addr               := core.io.axi_req_o_aw_bits_addr
    out.aw.bits.len                := core.io.axi_req_o_aw_bits_len
    out.aw.bits.size               := core.io.axi_req_o_aw_bits_size
    out.aw.bits.burst              := core.io.axi_req_o_aw_bits_burst
    out.aw.bits.lock               := core.io.axi_req_o_aw_bits_lock
    out.aw.bits.cache              := core.io.axi_req_o_aw_bits_cache
    out.aw.bits.prot               := core.io.axi_req_o_aw_bits_prot
    out.aw.bits.qos                := core.io.axi_req_o_aw_bits_qos
    // unused signals
    assert(core.io.axi_req_o_aw_bits_region === 0.U)
    assert(core.io.axi_req_o_aw_bits_atop === 0.U)
    assert(core.io.axi_req_o_aw_bits_user === 0.U)

    core.io.axi_resp_i_w_ready     := out.w.ready
    out.w.valid                    := core.io.axi_req_o_w_valid
    out.w.bits.data                := core.io.axi_req_o_w_bits_data
    out.w.bits.strb                := core.io.axi_req_o_w_bits_strb
    out.w.bits.last                := core.io.axi_req_o_w_bits_last
    // unused signals
    assert(core.io.axi_req_o_w_bits_user === 0.U)

    out.b.ready                    := core.io.axi_req_o_b_ready
    core.io.axi_resp_i_b_valid     := out.b.valid
    core.io.axi_resp_i_b_bits_id   := out.b.bits.id
    core.io.axi_resp_i_b_bits_resp := out.b.bits.resp
    core.io.axi_resp_i_b_bits_user := 0.U // unused

    core.io.axi_resp_i_ar_ready    := out.ar.ready
    out.ar.valid                   := core.io.axi_req_o_ar_valid
    out.ar.bits.id                 := core.io.axi_req_o_ar_bits_id
    out.ar.bits.addr               := core.io.axi_req_o_ar_bits_addr
    out.ar.bits.len                := core.io.axi_req_o_ar_bits_len
    out.ar.bits.size               := core.io.axi_req_o_ar_bits_size
    out.ar.bits.burst              := core.io.axi_req_o_ar_bits_burst
    out.ar.bits.lock               := core.io.axi_req_o_ar_bits_lock
    out.ar.bits.cache              := core.io.axi_req_o_ar_bits_cache
    out.ar.bits.prot               := core.io.axi_req_o_ar_bits_prot
    out.ar.bits.qos                := core.io.axi_req_o_ar_bits_qos
    // unused signals
    assert(core.io.axi_req_o_ar_bits_region === 0.U)
    assert(core.io.axi_req_o_ar_bits_user === 0.U)

    out.r.ready                    := core.io.axi_req_o_r_ready
    core.io.axi_resp_i_r_valid     := out.r.valid
    core.io.axi_resp_i_r_bits_id   := out.r.bits.id
    core.io.axi_resp_i_r_bits_data := out.r.bits.data
    core.io.axi_resp_i_r_bits_resp := out.r.bits.resp
    core.io.axi_resp_i_r_bits_last := out.r.bits.last
    core.io.axi_resp_i_r_bits_user := 0.U // unused
  }
}
